### ISSUE TITLE
Arabic in marcxml is entitized

### ISSUE THREAD

**Issue by eshadatta** [NYULibraries/dlts-aco-marc2mods#1]
@jgpawletko ,

Hi Joe,

I was looking at one of the marcxml and instead of the arabic, I see entities. Is there a way to change to UTF-8 encoding? For example:

```
<subfield code="a">&#1575;&#1604;&#1603;&#1578;&#1575;&#1576; &#1575;&#1604;&#1605;&#1602;&#1583;&#1587; &#1575;&#1610; &#1603;&#1578;&#1576; &#1575;&#1604;&#1593;&#1607;&#1583; &#1575;&#1604;&#1602;&#1583;&#1610;&#1605; &#1608; &#1575;&#1604;&#1593;&#1607;&#1583; &#1575;&#1604;&#1580;&#1583;&#1610;&#1583;.</subfield>
```

**Edited**:
Working on using a gem to decode the sample marcxml

**Comment by jgpawletko** [comment]
@eshadatta 
Hi Esha,
The MARCXML in the `marcxml/` directory is what I get after KARMS processing.
I don't know if this is helpful, but I added a `partner-marcxml` directory with the source
MARCXML as received from the partner, pre-KARMS processing.
The partner MARCXML is easier to read.
Best-
Joe

**Comment by eshadatta** [comment]
@jgpawletko , perfect, that's exactly what I needed. Thanks!
